### ISSUE TITLE
Mono Mp3 files

### ISSUE THREAD

**Issue by NGame1** [Amrykid/UWPShoutcastMSS#3]
Hi there . 
I found a little issue with mono (One Channel) Music files . 
If you play them you can see that the music plays with a 2x speed . 
this can be a good sample
http://208.85.243.222/radiojavan_low

**Comment by AzureKitsune** [comment]
I'll be honest. I had no idea what I was doing when I created this. I was hoping that someone with more knowledge would be able to help out, with this serving as a starting point.

Anyway, on topic: I seem to have stereo hardcoded in so I'll need to figure out a way to detect how many audio channels are in the stream.
[Line in question](https://github.com/Amrykid/UWPShoutcastMSS/blob/master/src/UWPShoutcastMSS/Streaming/ShoutcastMediaSourceManager.cs#L89)
`MediaStreamSource = new Windows.Media.Core.MediaStreamSource(new AudioStreamDescriptor(AudioEncodingProperties.CreateMp3(sampleRate, 2, (uint)bitRate)));`

**Comment by AzureKitsune** [comment]
Specifying of audio channel number has been added so this may have solved this issue for you. The url you have provided seems to be down atm.
