### ISSUE TITLE
SHOUTcast Server v2.4.7.256/posix(linux x86) 

### ISSUE THREAD

**Issue by nahuelproietto** [Amrykid/UWPShoutcastMSS#4]
Hello, i try to connect a Shoutcast v 2 to my player, but i doesn't response. I'm doing something wrong or it hasn't support?. Works fine on Shoutcast v1.  Many thanks, Nahuel.

**Comment by nahuelproietto** [comment]
Sorry, i noticed... content type audio/aacp. Thats all!.

**Comment by AzureKitsune** [comment]
I actually just figured out how to support AAC. I'll bring it over to this repo tonight.

#1

**Comment by nahuelproietto** [comment]
Great! i'll check later.

**Comment by AzureKitsune** [comment]
@nahuelproietto This should be all good to go.

**Comment by nahuelproietto** [comment]
Yes, it works!. Tested last night. Thanks!
